### ISSUE TITLE
Relaunch, any improvements?

### ISSUE THREAD

**Issue by franciscop** [Marak/translate.js#20]
Hi everyone, I've been talking with Marak about fixing and modernizing this project. If [you peak over the `modern` branch](https://github.com/Marak/translate.js/tree/modern) you can see that I made a lot of changes. Namely:

- Converted to **Promises** for async/await. I love this new feature and I find the workflow much better, specially for this use-case.
- **Multiple engines**: Yandex is already implemented, Google Translate will follow shortly as the default (trying to get a Key in my country) and Bing will probably follow those. Unfortunately all of those need a Key and couldn't find a decent translation API without a key. Adding a new engine is really easy as well but undocumented now.
- **Local translations**: Now you can provide your own translations, with a fallback from Google Translate.
- **Testing** with jest to make sure everything is working. This will be loaded into CircleCI so anyone can relaunch it at any point, avoiding the situation of deprecated APIs.
- Using **webpack+babel** as a build tool. This gives a tiny code and things properly working in older browsers. Some tweaks done to ensure native `fetch()` is used browser-side and `node-fetch` package on Node.js.

See a couple of examples from the documentation:

```js
// Browser; jQuery for demonstration purposes
$('#translate').submit(async e => {
  e.preventDefault();
  const text = $('.text').text();
  const spanish = await translate(text, { to: 'es' });
  alert(spanish);
});

// Node.js; serverjs.io example for demonstration purposes
const route = async ctx => {
  const spanish = await translate(ctx.body, { to: 'es' });
  return send(spanish);
};
```

There are few things that I'd love to implement in the future, like *bulk translation*, but I think it's better to keep it into a separated release as the scope for the first 1.0.0 version is quite neat as-is.

**What do you think? Am I missing anything important?**

**Comment by Marak** [comment]
You should make translate class under the hood to wrap singleton API.

When you have API such as:

```js
translate.engine = 'google';
translate.key = 'YOUR-KEY-HERE';
```

it makes it not possible to connect to multiple engines at once.

It's better to have constructor to create `new` instance of translate then perform calls. Default API should wrap constructor so user doesn't have to call `new` keyword with default usage.

**Comment by Marak** [comment]
I think that https://github.com/Marak/translate.js/blob/modern/src/add.js should be removed, as well as any notation of doing local based translations since it's out of scope.

Anything that is storing saved translations and bringing them back later is essentially an `i18n` library like: https://github.com/i18next/i18next or https://github.com/jeresig/i18n-node-2.

It would be better to focus on being able to communicate with multiple translation APIs versus trying to rebuild an `i18n` library.

**Comment by franciscop** [comment]
I allow for parameter-based arguments already:

```js
translate('Hello world', { to: 'es', engine: 'yandex' });
```

Could you provide a small example of the **usage** of per-instance please? Do you mean similar to how [memory-cache](https://www.npmjs.com/package/memory-cache) works, with the general `cache` and then able to create new instances with `var newCache = new cache.Cache();`?

In case it is related, you can currently set several keys:

```js
translate.keys = {
  google: 'key1',
  yandex: 'key2'
};
```

Then it will grab the correct one depending on the `engine` option, which can be set globally or per-translation. Having two keys for the same engine is IMHO a situation so unlikely that it doesn't make sense for the extra complexity it'd bring, and I haven't documented the multiple keys yet because even that seems a bit overkill at this point. It is also possible per-translation as an argument.

I agree that the `.add()` is a bit out of scope. For me it's still an important feature and it reuses the cache layer so it's light and integrates seamlessly. But it's really simple compared to the libraries that you linked.

I will dig deeper into i18next to see if there's a way to provide some glue to integrating both of them nicely. I really like the concept of having Google Translate as a fallback when there's no local translation yet. Also I could just create it in user-land when needed (on my own code).

**Comment by Marak** [comment]
Sure, `memory-cache` seems like it has constructor API. You can hide this
in background to preserve simple translate API and only expose if user
needs to make multiple instances.

It's not unlikely situation. Users will want to use multiple engines at
once or multiple keys at once for same provider. It's better design to make
class to represent connection and expose class for construction to user.
Not that complex.

Cache layer is out of scope completely IMO, what you are describing
is memoize. Better to use another library for caching.

**Comment by franciscop** [comment]
> Users will want to use [...] multiple keys at once for same provider.

I really fail to see this. The typical user is using a single engine (probably Google, the default) and has more than enough with this.

Then there might be some more adventurous users who try different engines; Yandex being Russian is probably better suited for this language. This I would say is a minority but still significant enough to justify being able to switch the engine.

Some of these will want to use two or more engines at the same time. Fine, easy to do right now, provide the keys and then specify the engine when you make a call.

But I have a hard time seeing how the average dev, in a single context, could want to put two different API keys for Google and run two different instances at the same time. Please tell me some realistic use-case for this (AKA a significat user portion fall into it). For the couple of devs who might actually need it they probably can create a thin wrapper with no problem at all to avoid passing the key in every call.

I think it doesn't make sense to complicate the design for a really obscure user-case so I'll leave that part as-is. I'll work on the i18n integration though and getting the Google engine fixed.

**Comment by Marak** [comment]
It's okay. I've had this exact same API issue and requirement get requested over Github Issues in probably 10x of my projects I can remember. You don't want to scope variable to module for something that should be instance variable.

If you can't make the prototype class or don't know how I will do a simple PR when you are done. It's not hard to add.

**Comment by Marak** [comment]
Let me know when you have API complete and tests passing.

If you are making library modern please also include code coverage tool and scripts ( `nyc` is preferred )

**Comment by franciscop** [comment]
Sure, I got the tests passing on my end. You'll need an `.env` file with the keys for testing, let me add that when I am finishing it. I think Webpack might be adding some noise for the coverage and that's why I didn't include it yet but I'll try to get it fixed when I improve the tests.

**Comment by Marak** [comment]
You probably want to mock responses from providers and use those in the tests instead.

I think https://github.com/node-nock/nock is good

**Comment by franciscop** [comment]
I got Google and Yandex working with the separated instances that you wanted. Coverage is 95% for all the files and it's included with the default `npm test`.

You can run all the tests and they are mocked, for the real thing Google and Yandex keys are would be added within the `.env`. Provided an example of the format on `.env.example`.

Tests and documentation can be improved, but **I think it'd be a good idea to release the first version** so people can start to test it. Tests are a bit buggy from the mocking library, but the mocked tests+manual testing show that it works great.

PS, I found Google was REALLY difficult to set up compared to Yandex. If I was still living in Spain I couldn't even have used the API since their migration to Business-only there. Fortunately in Japan it's still Business OR Individuals. Still have to try Bing translate but I'd wait for version 1.1.

**Comment by franciscop** [comment]
@Marak please check your SPAM box in your email :sweat_smile:
